### ISSUE TITLE
Broken link to Open Context

### ISSUE THREAD

**Issue by ekansa** [sibbr/DarwinCoreBrasil#194]
Hello! 

I happened to notice (via our logs) that there's a broken link to Open Context in this documentation. 

https://github.com/sibbr/DarwinCoreBrasil/blob/7d7ee42c53e2877f4e1214123cb6a43f62cd2c80/regras-validacao/regras.md?plain=1#L1927

This resource doesn't exist, and I suspect the Open Context URI/URL got truncated or miscopied at some point because '768A875F-E205-4D0B-DE55-BAB7598D0FD19' is not a valid UUID. 

Anyway, I have some background on using Open Context to indicate geospatial context information with DarwinCore, and suspect the example link should be: https://opencontext.org/subjects/e54377f7-4452-4315-b676-40679b10c4d9

or : https://opencontext.org/subjects/b5f813a9-4273-4725-8885-80176be5668e

**Comment by kguidonimartins** [comment]
Thanks, @ekansa! We are mirroring official contents from the TDWG: https://github.com/tdwg/bdq/projects/2

So we have to keep this error for now. Can you please suggest the correct link in this issue (which is the source of the error you reported): https://github.com/tdwg/bdq/issues/40 

I'm closing this issue for now. Feel free to reopen if needed.

Thanks again!

**Comment by ekansa** [comment]
Thanks @kguidonimartins for the suggestion and fixing this in your documentation. Here's my issue report to that other repo: https://github.com/tdwg/bdq/issues/294
